application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      vc-app-builder-runtime-api:
        license: Apache-2.0
        actions:
          VC-D365-API:
            function: actions/VC-D365-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              D365_APP_ID: $D365_APP_ID
              D365_API_URL: $D365_API_URL
              D365_CLIENT_ID: $D365_CLIENT_ID
              D365_GRANT_TYPE: $D365_GRANT_TYPE
              D365_CLIENT_SECRET: $D365_CLIENT_SECRET
              D365_SAT_APP_ID: $D365_SAT_APP_ID
              D365_SAT_API_URL: $D365_SAT_API_URL
              D365_SAT_CLIENT_ID: $D365_SAT_CLIENT_ID
              D365_SAT_GRANT_TYPE: $D365_SAT_GRANT_TYPE
              D365_SAT_CLIENT_SECRET: $D365_SAT_CLIENT_SECRET
              D365_SAT3_US_APP_ID: $D365_SAT3_US_APP_ID
              D365_SAT3_US_API_URL: $D365_SAT3_US_API_URL
              D365_SAT3_US_CLIENT_ID: $D365_SAT3_US_CLIENT_ID
              D365_SAT3_US_GRANT_TYPE: $D365_SAT3_US_GRANT_TYPE
              D365_SAT3_US_CLIENT_SECRET: $D365_SAT3_US_CLIENT_SECRET
              D365_SAT3_UK_EU_APP_ID: $D365_SAT3_UK_EU_APP_ID
              D365_SAT3_UK_EU_API_URL: $D365_SAT3_UK_EU_API_URL
              D365_SAT3_UK_EU_CLIENT_ID: $D365_SAT3_UK_EU_CLIENT_ID
              D365_SAT3_UK_EU_GRANT_TYPE: $D365_SAT3_UK_EU_GRANT_TYPE
              D365_SAT3_UK_EU_CLIENT_SECRET: $D365_SAT3_UK_EU_CLIENT_SECRET
              D365_PRODUCTION_APP_ID: $D365_PRODUCTION_APP_ID
              D365_PRODUCTION_API_URL: $D365_PRODUCTION_API_URL
              D365_PRODUCTION_CLIENT_ID: $D365_PRODUCTION_CLIENT_ID
              D365_PRODUCTION_GRANT_TYPE: $D365_PRODUCTION_GRANT_TYPE
              D365_PRODUCTION_CLIENT_SECRET: $D365_PRODUCTION_CLIENT_SECRET
              SESSION_SECRET: $SESSION_SECRET
              AVALARA_API_URL: $AVALARA_API_URL
              AVALARA_TOKEN: $AVALARA_TOKEN
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
          VC-D365-CONFIG:
            function: actions/VC-D365-CONFIG/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              D365_APP_ID: $D365_APP_ID
              D365_API_URL: $D365_API_URL
              D365_CLIENT_ID: $D365_CLIENT_ID
              D365_GRANT_TYPE: $D365_GRANT_TYPE
              D365_CLIENT_SECRET: $D365_CLIENT_SECRET
              D365_SAT_APP_ID: $D365_SAT_APP_ID
              D365_SAT_API_URL: $D365_SAT_API_URL
              D365_SAT_CLIENT_ID: $D365_SAT_CLIENT_ID
              D365_SAT_GRANT_TYPE: $D365_SAT_GRANT_TYPE
              D365_SAT_CLIENT_SECRET: $D365_SAT_CLIENT_SECRET
              D365_SAT3_US_APP_ID: $D365_SAT3_US_APP_ID
              D365_SAT3_US_API_URL: $D365_SAT3_US_API_URL
              D365_SAT3_US_CLIENT_ID: $D365_SAT3_US_CLIENT_ID
              D365_SAT3_US_GRANT_TYPE: $D365_SAT3_US_GRANT_TYPE
              D365_SAT3_US_CLIENT_SECRET: $D365_SAT3_US_CLIENT_SECRET
              D365_SAT3_UK_EU_APP_ID: $D365_SAT3_UK_EU_APP_ID
              D365_SAT3_UK_EU_API_URL: $D365_SAT3_UK_EU_API_URL
              D365_SAT3_UK_EU_CLIENT_ID: $D365_SAT3_UK_EU_CLIENT_ID
              D365_SAT3_UK_EU_GRANT_TYPE: $D365_SAT3_UK_EU_GRANT_TYPE
              D365_SAT3_UK_EU_CLIENT_SECRET: $D365_SAT3_UK_EU_CLIENT_SECRET
              D365_PRODUCTION_APP_ID: $D365_PRODUCTION_APP_ID
              D365_PRODUCTION_API_URL: $D365_PRODUCTION_API_URL
              D365_PRODUCTION_CLIENT_ID: $D365_PRODUCTION_CLIENT_ID
              D365_PRODUCTION_GRANT_TYPE: $D365_PRODUCTION_GRANT_TYPE
              D365_PRODUCTION_CLIENT_SECRET: $D365_PRODUCTION_CLIENT_SECRET
              SESSION_SECRET: $SESSION_SECRET
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
          VC-Boomi-API:
            function: actions/VC-Boomi-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              BOOMI_API_URL: $BOOMI_API_URL
              V1_BOOMI_API_KEY: $V1_BOOMI_API_KEY
              V1_D365_BOOMI_API_KEY: $V1_D365_BOOMI_API_KEY
              V1_TRACK_NOTIFY_BOOMI_API_KEY: $V1_TRACK_NOTIFY_BOOMI_API_KEY
              V2_BOOMI_API_KEY: $V2_BOOMI_API_KEY
              BOOMI_API_KEY: $BOOMI_API_KEY
              SESSION_SECRET: $SESSION_SECRET
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true    
          VC-PartnerInsight-API:
            function: actions/VC-PartnerInsight-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              PARTNER_INSIGHT_API_URL: $PARTNER_INSIGHT_API_URL
              PARTNER_INSIGHT_API_KEY: $PARTNER_INSIGHT_API_KEY
              WSP_GETACCOUNT_API_URL: $WSP_GETACCOUNT_API_URL
              WSP_GETACCOUNT_API_KEY: $WSP_GETACCOUNT_API_KEY
              SESSION_SECRET: $SESSION_SECRET
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
          VC-Magento-API:
            function: actions/VC-Magento-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              MAGENTO_API_URL: $MAGENTO_API_URL
              MAGENTO_API_TOKEN: $MAGENTO_API_TOKEN
              MAGENTO_BEARER_TOKEN: $MAGENTO_BEARER_TOKEN
              SESSION_SECRET: $SESSION_SECRET
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
          VC-Avalara-API:
            function: actions/VC-Avalara-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              AVALARA_CLIENT_ID: $AVALARA_CLIENT_ID
              AVALARA_CLIENT_SECRET: $AVALARA_CLIENT_SECRET
              AVALARA_GRANT_TYPE: $AVALARA_GRANT_TYPE
              AVALARA_SCOPE: $AVALARA_SCOPE
              AVALARA_TOKEN_URL: $AVALARA_TOKEN_URL
              AVALARA_RESOLVE_URL: $AVALARA_RESOLVE_URL
              SESSION_SECRET: $SESSION_SECRET
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
          VC-Payment-Methods-API:
            function: actions/VC-Payment-Methods-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
              FISERV_USB_API_URL: $FISERV_USB_API_URL
              FISERV_USB_API_KEY: $FISERV_USB_API_KEY
              FISERV_USB_X_APPLICATION_NAME: $FISERV_USB_X_APPLICATION_NAME
              FISERV_USB_X_APPLICATION_NAME_WHOLESALE: $FISERV_USB_X_APPLICATION_NAME_WHOLESALE
              FISERV_USB_X_APPLICATION_NAME_RETAIL: $FISERV_USB_X_APPLICATION_NAME_RETAIL
              FISERV_USB_LIST_PATH: $FISERV_USB_LIST_PATH
              FISERV_USB_DELETE_PATH: $FISERV_USB_DELETE_PATH
              FISERV_USB_ADD_PATH: $FISERV_USB_ADD_PATH
              FISERV_USB_RSA_PUBLIC_KEY: $FISERV_USB_RSA_PUBLIC_KEY
              FISERV_RSA_PUBLIC_KEY: $FISERV_RSA_PUBLIC_KEY
              WSP_GETACCOUNT_API_URL: $WSP_GETACCOUNT_API_URL
              WSP_GETACCOUNT_API_KEY: $WSP_GETACCOUNT_API_KEY
              WSP_GETACCOUNT_API_PATH: $WSP_GETACCOUNT_API_PATH
              SESSION_SECRET: $SESSION_SECRET
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
          Get-Session-Token:
            function: actions/Get-Session-Token/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: $LOG_LEVEL
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
