application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      vc-app-builder-runtime-api:
        license: Apache-2.0
        actions:
          VC-D365-API:
            function: actions/VC-D365-API/index.js
            web: secure
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              D365_API_URL: $D365_API_URL
              D365_API_KEY: $D365_API_KEY
            annotations:
              web-export: true
              raw-http: true
              require-adobe-auth: false
              final: true
